services:
  mysql:
    image: mysql:8.4
    container_name: restaurante_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: restaurante_pos_db
      MYSQL_USER: restaurante_user
      MYSQL_PASSWORD: restaurante_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  adminer:
    image: adminer:latest
    container_name: restaurante_adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
